# Generated by Django 5.0.3 on 2024-03-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidocter', '0003_alter_chatlist_created_at_alter_chatlist_last_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlist',
            old_name='last_chat',
            new_name='last_message',
        ),
    ]
