# Generated by Django 5.0.3 on 2024-03-28 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidocter', '0005_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
