# Generated by Django 5.0.3 on 2024-03-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidocter', '0008_chathistory_chat_list_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='chat_list_id',
            new_name='chat_list',
        ),
    ]
