# Generated by Django 5.0.3 on 2024-03-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidocter', '0002_chatlist_last_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatlist',
            name='last_chat',
            field=models.TextField(default='', null=True),
        ),
    ]
